blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pingtai.urls")),
    path('auth/', include("userauth.urls")),
    path('self/', include("self.urls")),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),   #富文本编辑器
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/self/urls.py
from django.urls import path,include
from . import views
app_name='self'
urlpatterns = [
    path('', views.index,name='index'),
    path('liuyan/',views.Liuyan,name="liuyan"),
    path('setinfo/', views.SetInfo, name="setinfo"),
    path('guanli/', views.guanli, name="guanli"),
    path('myselfInfo/', views.myselfInfo, name="myselfInfo"),
    path('upload/', views.upload, name="upload"),
    path('Addarticle/', views.Addarticle, name="Addarticle"),
    path('Lookarticle/', views.Lookarticle, name="Lookarticle"),
    path('/<int:id>/Delarticle/', views.Delarticle, name="Delarticle"),
    path('/<int:id>/XQarticle/', views.XQarticle, name="XQarticle"),
    path('/<int:id>/Pinglun/', views.Pinglun, name="Pinglun"),
    path('LookPinglun/', views.LookPinglun, name="LookPinglun"),
]

blog/self/models.py
from django.db import models
from userauth.models import User
from ckeditor.fields import RichTextField
from pingtai.models import Category,Keyword
# Create your models here.
# class Fans(models.Model):
# # # # # # #     name=models.CharField(max_length=20)
# # # # # # #     fans=models.IntegerField()
# # # # # # #     star=models.ForeignKey(to=User,on_delete=models.CASCADE)
# # # # # # #     img=models.ImageField(max_length=50)
# # # # # # #     zhuye=models.CharField(max_length=50)
class Article(models.Model):    #文章管理
    c = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name="分类")
    k=models.ForeignKey(to=Keyword,on_delete=models.CASCADE,verbose_name="关键字")
    a=models.ForeignKey(to=User,on_delete=models.CASCADE,verbose_name="作者")
    title=models.CharField(max_length=50,verbose_name="文章标题")
    con=RichTextField('文章内容')   #使用富文本编辑器
    c_time=models.DateTimeField(auto_now_add=True)
    u_time=models.DateTimeField(auto_now=True)
    liuyan=models.CharField(max_length=100,null=True)
    class Meta:
        verbose_name = "文章管理"
        verbose_name_plural = "文章管理"
    status=models.BooleanField(default=0,verbose_name='是否发表')

blog/self/forms.py
from userauth.models import User
from django import forms
from .models import Article
class Articleform(forms.ModelForm):
    class Meta:
        model=Article
        fields=['k','c','title','con','status']
        widgets={
            # 'a':forms.HiddenInput(),
            'c':forms.Select(attrs={
                'class':'ckt'
            }),
            'k':forms.Select(attrs={
                'class':'ckt'
            }),
            'title':forms.TextInput(attrs={
                'class':'ckt'
            }),
            'con':forms.TextInput(),
            'status':forms.CheckboxInput()

        }
    # def clean(self):  # 钩子函数首先执行
    #     cleaned_data = super().clean()

blog/self/views.py
from django.shortcuts import render,redirect,reverse
from authuser import authuser
from django.http import HttpResponse,JsonResponse
from userauth.models import User
from .models import Article
# Create your views here.
from authuser.authuser import Authuser
from .forms import Articleform
from django.views.decorators.csrf import csrf_exempt
@Authuser
def index(request):
    username=request.session.get("username",None)
    user=User.objects.filter(username=username).first()
    for item in user.article_set.all():
        ping=item.liuyan[:-1:1]
        ping1=ping.split("|")
    if request.method=="GET":
        return render(request,'self/myself.html',{'username':username,'user':user,'ping':ping1})
@Authuser
def Liuyan(request):
    username = request.session.get("username", None)
    if request.method == "GET":
        return render(request, "self/liuyan.html", {'username': username})
@Authuser
def SetInfo(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    if request.method == "GET":
        return render(request, "self/setinfo.html", {'username': username,'user':user})
@Authuser
def admin(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    if request.method == "GET":
        return render(request, "self/setinfo.html", {'username': username,'user':user})

# @Authuser
# def selfinfo(request):
#     username = request.session.get("username", None)
#     user = User.objects.filter(username=username).first()
#     if request.method == "GET":
#         return render(request, "self/setinfo.html", {'username': username, 'user': user})
@Authuser
def guanli(request):
    if request.method=='GET':
        username = request.session.get("username", None)
        return render(request,'self/index.html',{'username':username})

@Authuser
def myselfInfo(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    if request.method=='GET':
        return  render(request,'self/myselfInfo.html',{'user':user})

@Authuser
def upload(request):
    username = request.session.get("username", None)
    if request.method=="POST":
        img=request.FILES['img']
        name=request.POST.get('name')
        tel=request.POST.get('tel')
        email=request.POST.get('email')
        password=request.POST.get('password')
        # print(dir(img))
        with open('media/userhead/%s'%img.name,'wb+') as destination:
            for chunk in img.chunks():
                destination.write(chunk)
        User.objects.filter(username=username).update(username=name, tel=tel, email=email, password=password,img='/media/userhead/%s' % img.name)
        return redirect(reverse("self:myselfInfo"))
# @Authuser
# def Addarticle(request):
#     username = request.session.get("username", None)
#     if request.method=="GET":
#         aid = User.objects.filter(username=username).first().id
#         form = Articleform({'a': aid})
#         return render(request,'self/Addarticle.html',{'form':form})
#     else:
#         # print(request.POST)打印请求回来的信息
#         form=Articleform(request.POST)
#         #print(form.errors)    #打印form验证出现的问题
#         if form.is_valid():
#             # obj=form.save(commit=False)
#             # obj.a.add(aid)
#             # obj.save()
#             form.save()
#         return render(request,'self/Addarticle.html',{'form':form})
@Authuser
def Addarticle(request):
    username = request.session.get("username", None)
    if request.method=="GET":
        form = Articleform()
        return render(request,'self/Addarticle.html',{'form':form})
    else:
        # print(request.POST)打印请求回来的信息
        form=Articleform(request.POST)
        #print(form.errors)    #打印form验证出现的问题
        if form.is_valid():
            aid = User.objects.filter(username=username).first().id
            obj=form.save(commit=False)
            obj.a_id=aid
            obj.save()
        return render(request,'self/Addarticle.html',{'form':form})
@Authuser
def Lookarticle(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    articles=user.article_set.all()
    if request.method=="GET":
        return render(request,'self/Lookarticle.html',{'articles':articles})
@Authuser
def Delarticle(request,id):
    Article.objects.filter(id=id).delete()
    return redirect(reverse("self:Lookarticle"))
@Authuser
def XQarticle(request,id):
    article=Article.objects.filter(id=id).first()
    return render(request,"self/XQarticle.html",{'article':article})
@Authuser
def Pinglun(request,id):
    pinglun=request.POST.get("pinglun")
    import jieba
    import re
    import numpy as np
    from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
    from sklearn.feature_extraction.text import TfidfVectorizer

    def textParse1(lines):
        lines = re.sub(r'[a-zA-Z.【】0-9、。，@（）+""“”,:<>()：|？?\[\]\-/！…~\*\n]', '', lines)
        words = jieba.lcut(lines)
        new = [[w for w in words if len(w)>1]]
        document = [" ".join(sent) for sent in new]
        return document

    wordlist = []
    classlist = []
    for i in range(127):
        wordlist_s = textParse1(open('media/shuju/laji/%d.txt' % i, encoding='utf8').read())
        wordlist.append(','.join(wordlist_s))
        classlist.append(1)
    for i in range(29):
        wordlist_s = textParse1(open('media/shuju/zhengchang/%d.txt' % i, encoding='utf8').read())
        wordlist.append(','.join(wordlist_s))
        classlist.append(0)
    tfidf1 = TfidfVectorizer()
    result1 = tfidf1.fit_transform(wordlist)
    result1 = result1.toarray()
    gn = GaussianNB()
    gn = gn.fit(np.array(result1), np.array(classlist))
    testWords = textParse1(pinglun)
    res1 = tfidf1.transform(testWords)
    res1 = res1.toarray()
    # print(type(gn.predict(res1)))
    # print(dir(gn.predict(res1)))
    # print(gn.predict(res1)[0])
    if gn.predict(res1)[0]==1:
        return HttpResponse("评论内容不符合规则,请审核后重新评论")
    else:
        article=Article.objects.filter(id=id).first()
        article.liuyan+=pinglun+"|"
        article.save()
        return redirect(reverse("self:index"))
@Authuser
@csrf_exempt
def LookPinglun(request):
    pass
    # if request.is_ajax():
    #     id=request.POST.get("id",None)
    #     obj=Article.objects.filter(id=id).first()
    #     str1=obj.liuyan
    #     print(type(str1))
    #     str2=str1[:-1]
    #     print(type(str2))

blog/self/templates/self/Addarticle.html
{% extends 'moban/guanliMoban.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'self/css/addArticle.css' %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'self/js/Getkey.js' %}"></script>
{% endblock %}
{% block main %}
        <div id="page-wrapper">
         <h1>发表文章</h1>
            <form action="{% url 'self:Addarticle' %}" id="form1" method="post">
                {% csrf_token %}
                {{ form.a }}
                <span class="span1">
                    {{ form.title.label }}:
                </span><br>
                {{ form.title }}<br>
                <span class="span1">
                    {{ form.c.label }}:
                </span><br>
                {{ form.c }}<br>
                <span class="span1">
                    {{ form.k.label }}:
                </span><br>
                {{ form.k }}<br>
                 <span class="span1">
                    {{ form.con.label }}:
                </span><br>
                {{ form.con }}<br>
                <span class="span1">
                    {{ form.status.label }}:
                </span>
                {{ form.status }}<br>
                <button>提交发表</button>
            </form>
       </div>
{% endblock %}

blog/self/templates/self/Lookarticle.html
{% extends 'moban/guanliMoban.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'self/css/addArticle.css' %}">
{#<link rel="stylesheet" href="{% static 'self/css/bootstrap.css' %}">#}
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}
{% block main %}
        <div id="page-wrapper">
         <h1>文章管理</h1>
            <table class="table table-striped">
                <tr>
                    <th>标题</th>
                    <th>分类</th>
                    <th>关键字</th>
                    <th>内容</th>
                    <th>状态</th>
                    <th>发布时间</th>
                    <th>操作</th>
                </tr>
                {% for item in articles %}
                     <tr>
                        <th>{{ item.title }}</th>
                        <th>{{ item.c }}</th>
                        <th>{{ item.k }}</th>
                        <th>{{ item.con }}</th>
                         <th>{{ item.status }}</th>
                         <th>{{ item.c_time }}</th>
                        <th><a href="{% url 'self:Delarticle' item.id %}">删除</a>
                            <a href="{% url 'self:XQarticle' item.id %}">查看详情</a>
                        </th>
                    </tr>
                {% endfor %}
            </table>
       </div>
{% endblock %}

blog/self/templates/self/XQarticle.html
{% extends 'moban/guanliMoban.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'self/css/XQarticle.css' %}">
{% endblock %}
{% block main %}
        <div id="page-wrapper">
            <div class="con2">
                <div class="title">
                    {{ article.title }}
                </div>
                <div class="time">
                    发布时间：{{ article.c_time }}
                </div>
                <div class="artcon">
                    {{ article.con | safe }}
                </div>
                <dev class="key">
                    关键字：{{ article.k }}
                </dev>
            </div>

       </div>
{% endblock %}

blog/self/templates/self/index.html
{% extends 'moban/guanliMoban.html' %}
{% block main %}
        <div id="page-wrapper">
       </div>
{% endblock %}

blog/self/templates/self/liuyan.html
 {% extends 'moban/mobanHtml.html' %}
{% load static %}
{% block css%}
<link href="{% static 'self/css/liuyan.css' %}" rel="stylesheet">
{% endblock %}
 {% block main %}
<div class="blogitem">
    <h1>留言板</h1>
    <div class="son"></div>
    <div class="son"></div>
    <div class="son"></div>
    <div class="son"></div>
     <div class="son"></div>
    <div class="son"></div>
    <div class="son"></div>
    <div class="son"></div>
</div>
{% endblock %}

blog/self/templates/self/myself.html
 {% extends 'moban/mobanHtml.html' %}
{% load static %}
 {% block main %}
<div class="blogitem">
      {% for item in user.article_set.all %}
      <article>
        <h2 class="title"><a href="#">{{ item.title }}{{ item.id }}</a></h2>
        <ul class="text">
          <p>“陌上花开，可缓缓归矣。” 含义：（夫人），田间阡陌上的花开了，你可以一边赏花，一边慢慢地回来。</p>
          <p>“陌上花开，如果没有悄然伫立阡陌并为陌上风情所陶醉的人，那么花开也寂寞，风情也苍白....”喜欢这句话，是因为看了忍冬的作品《陌上花开缓缓归》</p>
          <p>阳春三月，风和日暖，信步城外，看阡陌之上的杨柳依依，野花绚烂，身心不由得轻爽而浪漫。“三月风情陌上花”，古远的诗句似乎随风从天边飘来，从历史的深处飘来，拂过阡陌，袭上心头，诗是属于清乾嘉诗人赵翼的，可昂首远望，眼前的陌上风情却是不折不扣的现代，由眼帘入心扉。</p>
          <p class="textimg"><img src="{% static 'self/images/text02.jpg' %}"></p>
          <p>漫步陌上，心情是诗意的那种，优雅而散淡，不惹匆促，只因陌上花开；花是自然的那种，朴素而恬淡，不落尘俗。“三月风情陌上花”，是花在其中生命得以璀璨，人在其中心情得以畅然的一种意境。三月陌上花，让人爱让人痴，恍惚人的骨子里头都沉淀了花的影子，花的风韵。</p>
          <p>陌上花开，如果没有了从俗累的生活中走出来，悄然伫立阡陌并为陌上风情所陶醉的人，那么花开也寂寞，风情也苍白。于是，一句“陌上花开，可缓缓归矣”不知被多少人吟诵了多少遍。人归缓缓，那花便有灵性，便开得执著，陌上风情也被撩拨得浓郁而热烈。</p>
          <p>缓缓归，缓缓归，披一袭“三月风情”，再采一束“陌上花”，缓缓归。</p>
          <p>缓缓归矣，我心已是陌上花开。</p>
             <form action="{% url 'self:Pinglun' item.id %}" class="sks" method="post">
                 {% csrf_token %}
                <textarea name="pinglun" id="" cols="100" rows="5" class="texta"></textarea>
                  <button class="submitt">提交</button>
            </form>
        </ul>
        <div class="textfoot">
          <a href="javascript:look({{ item.id }})" class="look">查看评论</a><span class="pinglun">评论</span><a href="#">转载</a>
        </div>
          {% for item1 in ping %}
        <div class="liu1">
            {{ item1 }}
        </div>
              {% endfor %}
      </article>
      {% endfor %}
</div>
{% endblock %}

blog/self/templates/self/myselfInfo.html
{% extends 'moban/guanliMoban.html' %}
{% load static %}
{% block css %}
<link href="{% static 'self/css/setinfo.css' %}" rel="stylesheet">
{% endblock %}
{% block main %}
      <div id="page-wrapper">
      <div class="blogitem">
         <h1>设置个人信息</h1>
          <span>头像：</span>
          <img src="{{ user.img }}" alt="" style="height: 200px;width: 200px;display: block">
            <form action="/self/upload/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
               <div class="son" style="height: 80px">
                   <input type="file" name="img" id="img">
              </div>
              <div class="son">
                  <span>昵称：</span><input type="text" value="{{ user.username }}" name="name">
              </div>
                <div class="son">
                  <span>联系方式：</span><input type="text" value="{{ user.tel }}" name="tel">
              </div>
            <div class="son">
                  <span>邮箱地址：</span><input type="email" value="{{ user.email }}" name="email">
              </div>
            <div class="son">
                  <span>用户密码：</span><input type="password" value="{{ user.password }}" name="password">
              </div>
                <button>提交</button>
            </form>
      </div>
       </div>
{% endblock %}

blog/self/templates/self/setinfo.html
 {% extends 'moban/mobanHtml.html' %}
{% load static %}
{% block css %}
<link href="{% static 'self/css/setinfo.css' %}" rel="stylesheet">
{% endblock %}
 {% block main %}
<div class="blogitem">
      <h1>设置个人信息</h1>
    <form action="">
      <div class="son">
          <span>昵称：</span><input type="text" placeholder="{{ user.username }}">
      </div>
        <div class="son">
          <span>联系方式：</span><input type="text" placeholder="{{ user.tel }}">
      </div>
    <div class="son">
          <span>邮箱地址：</span><input type="email" placeholder="{{ user.email }}">
      </div>
    <div class="son">
          <span>用户密码：</span><input type="password" placeholder="********">
      </div>
        <button>提交</button>
    </form>
</div>
{% endblock %}