blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pingtai.urls")),
    path('auth/', include("userauth.urls")),
    path('self/', include("self.urls")),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),   #富文本编辑器
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/pingtai/urls.py
from django.urls import path
from . import views
app_name="pingtai"
urlpatterns = [
    path('', views.index,name="index"),
    path('GetKeyword/',views.getKeyword,name="'GetKeyword"),
    path('/<int:id>/detial/',views.detial,name="detial"),
    path('Exitlogin/', views.Exitlogin, name="Exitlogin"),
    path('Kaitong/', views.Kaitong, name="Kaitong"),
    path('House/', views.House, name="House"),
    # {% url 'pingtai:detial' item.id %}
]

blog/self/urls.py
from django.urls import path,include
from . import views
app_name='self'
urlpatterns = [
    path('', views.index,name='index'),
    path('liuyan/',views.Liuyan,name="liuyan"),
    path('setinfo/', views.SetInfo, name="setinfo"),
    path('guanli/', views.guanli, name="guanli"),
    path('myselfInfo/', views.myselfInfo, name="myselfInfo"),
    path('upload/', views.upload, name="upload"),
    path('Addarticle/', views.Addarticle, name="Addarticle"),
    path('Lookarticle/', views.Lookarticle, name="Lookarticle"),
    path('/<int:id>/Delarticle/', views.Delarticle, name="Delarticle"),
    path('/<int:id>/XQarticle/', views.XQarticle, name="XQarticle"),
    path('/<int:id>/Pinglun/', views.Pinglun, name="Pinglun"),
    path('LookPinglun/', views.LookPinglun, name="LookPinglun"),
]

blog/userauth/urls.py
from django.urls import path
from . import views
app_name="auth"
urlpatterns = [
    path('login/', views.login,name="login"),
    path('register/', views.register,name="register"),
]

blog/pingtai/models.py
from django.db import models
from django.utils.html import format_html
from django.contrib.auth.models import User   #引入内部User用户模型
from ckeditor.fields import RichTextField     #引入富文本编辑器
from userauth.models import User as User1
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20,verbose_name="分类")
    def listKeyword(self):    #在model信息中显示出来
        objs=self.keyword_set.all()
        arr=[]
        for item in objs:
            arr.append("<e style='margin:0 5px'>"+item.name+"</e>")
        return format_html("".join(arr))  #转换成字符串形式，加上样式
    def __str__(self):
        return self.name
    @classmethod
    def getall(cls):
        return cls.objects.all()
    class Meta:
        verbose_name = "分类管理"
        verbose_name_plural = "分类管理"
class Keyword(models.Model):
    name=models.CharField(max_length=20,verbose_name="关键字")
    c=models.ForeignKey(to=Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
class PTArticle(models.Model):    #文章管理
    c = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name="分类")
    k=models.ForeignKey(to=Keyword,on_delete=models.CASCADE,verbose_name="关键字")
    a=models.ForeignKey(to=User,on_delete=models.CASCADE,verbose_name="作者")
    title=models.CharField(max_length=50,verbose_name="文章标题")
    con=RichTextField('文章内容')   #使用富文本编辑器
    c_time=models.DateTimeField(auto_now_add=True)
    u_time=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "文章管理"
        verbose_name_plural = "文章管理"
    status=models.BooleanField(default=0,verbose_name='是否发表')
class House(models.Model):
    dist=models.CharField(max_length=20,verbose_name='地区名')
    roomnum=models.IntegerField(verbose_name='面积')
    halls = models.IntegerField(
        choices=(
            (0, "low"),
            (1, "middle"),
            (2, 'high  ')
        ),
        default=0, verbose_name="层级"
    )

class UserInfo(models.Model):
    u=models.OneToOneField(to=User1,on_delete=models.CASCADE,verbose_name="用户昵称")
    company=models.CharField(max_length=30,verbose_name="所在公司")
    position=models.CharField(max_length=30,verbose_name="职位")
    hobby=models.CharField(max_length=100,verbose_name="爱好")
    reason=models.CharField(max_length=200,verbose_name="申请原因")
    realname=models.CharField(max_length=20,verbose_name="真实姓名")
    c_time=models.DateTimeField(auto_now_add=True,verbose_name="申请时间")
    u_time=models.DateTimeField(auto_now=True,verbose_name="处理时间")
    sh = models.IntegerField(
        choices=(
            (0, "未审核"),
            (1, "审核中"),
            (2, '审核完毕  ')
        ),
        default=0,verbose_name="审核状态"
    )

    class Meta:
        verbose_name = "审核管理"
        verbose_name_plural = "审核管理"

blog/pingtai/forms.py
from django import forms
from .models import UserInfo
class UserInfoForm(forms.ModelForm):
    class Meta:
        model=UserInfo
        fields="__all__"
        widgets={
            "u":forms.HiddenInput(),
            'sh':forms.HiddenInput(),
            'company':forms.TextInput(attrs={'class':'realname'}),
            'position':forms.TextInput(attrs={'class':'realname'}),
            'hobby':forms.TextInput(attrs={'class':'hobby'}),
            'reason':forms.TextInput(attrs={'class':'hobby'}),
            "realname":forms.TextInput(attrs={'class':'realname'})
        }

blog/pingtai/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,JsonResponse
from django.views.decorators.csrf import csrf_exempt   #引入ajax跨越
from .models import Keyword,Category,PTArticle
from userauth.models import User
from .forms import UserInfoForm
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
# Create your views here.
def index(request):
    if request.method=="GET":
        cate=Category.getall()
        ticle=PTArticle.objects.all()
        username=request.session.get('username', None)
        user=User.objects.filter(username=username).first()
        if username!=None:
            if user.sex=="男":
                sex=1
            else:
                sex=0
            df = pd.read_csv("media/shuju/logistic_dat.csv")
            df1 = pd.get_dummies(df["Gender"])
            del df1["Female"]
            df2 = pd.concat([df1, df], axis=1)
            del df2["User ID"]
            del df2["Gender"]
            X = df2.iloc[:, :-1]
            y = df2["Purchased"]
            clf = LogisticRegression(max_iter=1000000,tol=0.000000001)
            # clf.solver = "lbfgs"   报一个关于未来的提醒，未来会将默认更新为lbfgs,不用管这个提示
            clf = clf.fit(X, y)
            # print(clf.score(X,y))
            X=[sex,user.age,user.income]
            # print(X)
            result=int(clf.predict(np.array(X).reshape(1,-1)))
            print(result)
        else:
            result=0
        return render(request,"pingtai/pingtai.html",{"cate":cate,"ticle":ticle,"user":user,"result":result})
@csrf_exempt    #允许ajax跨越
def getKeyword(request):
    if request.is_ajax():    #是否为ajax请求
        c=request.POST.get("c")
        res=Keyword.objects.filter(c=c).values_list("id","name")   #.all()    .values()  .values_list()
        obj={}
        for index in res:
            obj[index[0]]=index[1]
        return JsonResponse(obj)
def detial(request,id):
    ticle=PTArticle.objects.filter(id=id).first()
    return render(request,"pingtai/xiangqing.html",{'ticle':ticle})
    # return render(request,"")
    # request.session['ydh']="12345"   #保存到数据时设置session,
def Exitlogin(request):
    del request.session['username']
    return redirect(reverse("pingtai:index"))
def Kaitong(request):
    username = request.session.get('username', None)
    if username:
        user=User.objects.filter(username=username).first()
        if request.method=="GET":
            form=UserInfoForm({'u':user.id,"sh":1},)
            return render(request,"pingtai/Kaitong.html",{'form':form})
        else:
            form=UserInfoForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect(reverse("pingtai:index"))
            else:
                return render(request, "pingtai/Kaitong.html", {'form': form})
    else:
        return HttpResponse("未登录")
def House(request):
    if request.method=="GET":
        return render(request,"pingtai/house.html")
    else:
        from sklearn.linear_model import LinearRegression
        df1 = pd.read_csv("media/shuju/house_price.csv")
        df2 = pd.get_dummies(df1[['dist', 'floor']])  # 虚拟变量,将汉字项转变为数字
        del df2['dist_chaoyang']  # 他们每一种中的分类之间的关系很大，需要删除一列
        del df2['floor_high']  # 两种就可以确定情况
        del df1['dist']
        del df1['floor']
        pd.set_option('display.max_columns', 20)  # 输出的最大列数，避免省略
        df = pd.concat([df2, df1], axis=1)
        # df.values()
        # print(df)
        X = df.iloc[:, :-1]
        y = df['price']
        reg = LinearRegression()
        reg = reg.fit(X, y)
        X = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dist=request.POST.get("dist")
        floor = request.POST.get("floor")
        roomnum = request.POST.get("roomnum")
        halls = request.POST.get("halls")
        area = request.POST.get("area")
        subway = request.POST.get("subway")
        school = request.POST.get("school")
        if dist!='no':
            X[int(dist)]=1
        if floor!='no':
            X[int(floor)]=1
        if roomnum!=None:
            X[7]=int(roomnum)
        if halls != None:
            X[8]=int(halls)
        if area!="":
            X[9]=int(area)
        if subway!=None:
            X[10]=int(subway)
        if school!=None:
            X[11]=int(school)
        # list=[16466.69306314 ,- 7180.93285997 ,13591.77537519 ,- 8418.94991321,
        #  28968.77046877 , 2005.70365381 , 1525.53686035 , 1092.23437222,
        #  4218.61495977, - 57.77458065 , 6967.01535292 ,11771.75879975]
        # a=40572.667946191206
        # result=0
        # for i in range(len(X)):
        #     result+=X[i]*list[i]
        # result=result+a
        result=str(reg.predict(np.array(X).reshape(1,-1)))
        result=float(result[1:-1])
        result=np.round(result,2) #设定精度
        return render(request, "pingtai/house.html",{'result':result})

blog/pingtai/templates/pingtai/Kaitong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    span{
        font-size: 18px;
    }
    .realname{
        width: 300px;
        height: 50px;
    }
    .hobby{
        width:500px;
        height: 100px;
    }
    button{
        width:100px ;
        height: 40px;
        margin-left: 20px;
        margin-top: 20px;
    }
</style>
<body>
<form action="/Kaitong/" method="post">
    {% csrf_token %}
    {{ form.u }}
    {{ form.sh }}
    <span>真实姓名:</span><br>
    {{ form.realname }}<br>
    <span>公司名称:</span><br>
    {{ form.company }}<br>
    <span>职位:</span><br>
    {{ form.position }}<br>
    <span>爱好:</span><br>
    {{ form.hobby }}<br>
    <span>申请缘由:</span><br>
    {{ form.reason }}<br>
    <button>提交</button>
</form>
</body>
</html>

blog/pingtai/templates/pingtai/house.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'pingtai/css/bootstrap.css' %}">
</head>
<style>
    .container{
        border:1px solid #ccc;
        margin-top: 10px;
        padding:20px;
        background-image: url("{% static '/pingtai/img/house2.jpg' %}");
    }
    h1{
        margin:0 auto;
        text-align: center;
    }
    .aa{
        color: #000;
        font-size: 21px;
    }
    .bb{
        color: #0ff39c;
    }
    .cc{
        width: 100px;
    }
</style>
<body>
<h1>房价预测查询</h1>
<div class="container">
<form action="/House/" method="post">
    {% csrf_token  %}
    <span class="aa">选择地区：</span>
    <select class="form-control" name="dist">
      <option value="no">朝阳</option>
      <option value="0">东城</option>
      <option value="1">丰台</option>
      <option value="2">海淀</option>
      <option value="3">石景山</option>
      <option value="4">西城</option>
    </select><br>
    <span class="aa">层级：</span>
     <select class="form-control" name="floor">
      <option value="no">高层</option>
      <option value="5">中层</option>
      <option value="6">底层</option>
    </select><br>
    <span class="aa">几室：</span>
    <select class="form-control" name="roomnum">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select><br>
    <span class="aa">几厅：</span>
    <select class="form-control" name="halls">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
    </select><br>
    <div class="form-group">
        <span class="aa">面积：</span>
        <input type="text" class="form-control" id="exampleInputName2" name="area">
    </div>
    <span class="aa">是否靠近地铁：</span>
    <label class="radio-inline">
        <input type="radio" name="subway" id="inlineRadio1" value="1"> 是
    </label>
    <label class="radio-inline">
        <input type="radio" name="subway" id="inlineRadio2" value="0"> 否
    </label>
    <span class="aa">是否靠近学校：</span>
    <label class="radio-inline">
        <input type="radio" name="school" id="inlineRadio1" value="1"> 是
    </label>
    <label class="radio-inline">
        <input type="radio" name="school" id="inlineRadio2" value="0"> 否
    </label>
    <button class="cc">查询</button>
</form>
<span class="aa">查询结果为：<span class="aa bb">{{ result }} </span>元</span>
</div>
</body>
</html>

blog/pingtai/templates/pingtai/pingtai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>咳咳平台</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/pingtai/css/pingtai.css' %}">
</head>
<style>
    #keke{
        background-image: url("{% static '/pingtai/img/chang.gif' %}");
    }
    #house{
        position: absolute;
        top:10px;
        left:0;
        right:0;
        margin: 0 auto;
        width: 500px;
        height: 100px;
        background-image: url("{% static '/pingtai/img/house.jpg' %}");
        background-size: 500px 100px;
        opacity: .8;
    }
    #house span{
        color: #fc9ac7;
        font-size: 21px;
        font-weight: 600;
    }
     #house .option{
         margin-top:70px;
         float:right;
     }
</style>
<body>
<nav>
    <div class="title">
        <div class="left">
            <span>咳咳</span>分享心情和最美的你...
        </div>
        <div class="right">
            {% if user %}
                <span>
                   欢迎<span style="color: #00a2d4;font-size: 18px">{{ user.username }}</span>|<a href="{% url 'self:index' %}">我的咳咳</a>|<a href="">短消息</a>|<a href="">设置</a>|<a href="{% url 'pingtai:Exitlogin' %}">注销</a>
                </span>
            {% else %}
                <span>
                    <a href="{% url 'auth:login' %}">登录</a>|<a href="{% url 'auth:register' %}">注册咳咳</a>
                </span>
            {% endif %}
        </div>
    </div>
</nav>
<header>
    <div id="keke">
        <li>
            <a href="">园子</a><a href="">新闻</a><a href="">博问</a><a href="">闪存</a><a href="">小组</a><a href="">收藏</a><a
                href="">招聘</a><a href="">班级</a><a href="">招聘</a>
        </li>
    </div>
</header>
<main>
    <div class="mainbox">
        <div class="left">
            <ul id="aside">
                {% include 'pingtai_moban/index_list.html' %}
            </ul>
        </div>
        <div class="moddle">
            <span>最新分享</span>
                {% for item in ticle %}
                <div class="con">
                    <div class="left1">
                        <div class="photo">
                            <img src="{% static '/pingtai/img/11.jpg' %}" alt="" height="200" width="200">
                        </div>
                    </div>
                    <div class="right1">
                        <h4><a href="{% url 'pingtai:detial' item.id %}">{{ item.title }}</a><span>[置顶]</span></h4>
                        <span id="aa">{{ item.u_time }}</span>
                        <p>{{ item.con | striptags | slice:":800" }}...</p>
                    </div>
                </div>
                {% endfor %}
{#            <div class="con"></div>#}
{#            <div class="con"></div>#}
{#            <div class="con"></div>#}
{#            <div class="con"></div>#}
            <div class="pages"><a href="">1</a><a href="#" hidefocus="">2</a><a href="#" hidefocus="">3</a><a href="#" class="next">下一页&gt;&gt;</a></div>
        </div>
        <div class="right">
            {% if user.userinfo.sh == 0 %}
            <div class="son1">
                <span>遇见更多朋友</span>
                <a href="{% url 'pingtai:Kaitong' %}">开通博客</a>
            </div>
            {% elif user.userinfo.sh == 1 %}
                <div class="son1">
                <span>遇见更多朋友</span>
                <a href="{% url 'pingtai:Kaitong' %}" class="shenhe">博客审核中</a>
               </div>
            {% elif user.userinfo.sh == 2 %}
            <div class="son1">
            <span>你已经加入了咳咳大家庭！一起分享吧！</span>
           </div>
           {% elif user.c == 0 %}
            <div class="son1">
            <span>遇见更多朋友</span>
            <a href="{% url 'pingtai:Kaitong' %}">开通博客</a>
           </div>
            {% endif %}
            <div class="son">
                <img src="{% static '/pingtai/img/guanggao1.jpg' %}" alt="" width="200" height="500">
            </div>
            <div class="son">
                 <img src="{% static '/pingtai/img/guanggao2.png' %}" alt="" width="200" height="500">
            </div>
        </div>
    </div>
</main>
{% if result == 1 %}
<div class="house" id="house">
    <span>想买房吗？还不快来看看!!!</span>
    <div class="option">
        <button><a href="{% url 'pingtai:House' %}">去看看</a></button>
        <button id="exit">算了，下次再说</button>
    </div>
</div>
{% endif %}
</body>
</html>
<script src="{% static 'pingtai/js/jquery-3.2.1.js' %}"></script>
<script>
$("#exit").on('click',function () {
    $("#house").css({'display':'none'})
})
</script>