blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pingtai.urls")),
    path('auth/', include("userauth.urls")),
    path('self/', include("self.urls")),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),   #富文本编辑器
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/pingtai/urls.py
from django.urls import path
from . import views
app_name="pingtai"
urlpatterns = [
    path('', views.index,name="index"),
    path('GetKeyword/',views.getKeyword,name="'GetKeyword"),
    path('/<int:id>/detial/',views.detial,name="detial"),
    path('Exitlogin/', views.Exitlogin, name="Exitlogin"),
    path('Kaitong/', views.Kaitong, name="Kaitong"),
    path('House/', views.House, name="House"),
    # {% url 'pingtai:detial' item.id %}
]

blog/self/urls.py
from django.urls import path,include
from . import views
app_name='self'
urlpatterns = [
    path('', views.index,name='index'),
    path('liuyan/',views.Liuyan,name="liuyan"),
    path('setinfo/', views.SetInfo, name="setinfo"),
    path('guanli/', views.guanli, name="guanli"),
    path('myselfInfo/', views.myselfInfo, name="myselfInfo"),
    path('upload/', views.upload, name="upload"),
    path('Addarticle/', views.Addarticle, name="Addarticle"),
    path('Lookarticle/', views.Lookarticle, name="Lookarticle"),
    path('/<int:id>/Delarticle/', views.Delarticle, name="Delarticle"),
    path('/<int:id>/XQarticle/', views.XQarticle, name="XQarticle"),
    path('/<int:id>/Pinglun/', views.Pinglun, name="Pinglun"),
    path('LookPinglun/', views.LookPinglun, name="LookPinglun"),
]

blog/userauth/urls.py
from django.urls import path
from . import views
app_name="auth"
urlpatterns = [
    path('login/', views.login,name="login"),
    path('register/', views.register,name="register"),
]

blog/self/models.py
from django.db import models
from userauth.models import User
from ckeditor.fields import RichTextField
from pingtai.models import Category,Keyword
# Create your models here.
# class Fans(models.Model):
# # # # # # #     name=models.CharField(max_length=20)
# # # # # # #     fans=models.IntegerField()
# # # # # # #     star=models.ForeignKey(to=User,on_delete=models.CASCADE)
# # # # # # #     img=models.ImageField(max_length=50)
# # # # # # #     zhuye=models.CharField(max_length=50)
class Article(models.Model):    #文章管理
    c = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name="分类")
    k=models.ForeignKey(to=Keyword,on_delete=models.CASCADE,verbose_name="关键字")
    a=models.ForeignKey(to=User,on_delete=models.CASCADE,verbose_name="作者")
    title=models.CharField(max_length=50,verbose_name="文章标题")
    con=RichTextField('文章内容')   #使用富文本编辑器
    c_time=models.DateTimeField(auto_now_add=True)
    u_time=models.DateTimeField(auto_now=True)
    liuyan=models.CharField(max_length=100,null=True)
    class Meta:
        verbose_name = "文章管理"
        verbose_name_plural = "文章管理"
    status=models.BooleanField(default=0,verbose_name='是否发表')

blog/self/forms.py
from userauth.models import User
from django import forms
from .models import Article
class Articleform(forms.ModelForm):
    class Meta:
        model=Article
        fields=['k','c','title','con','status']
        widgets={
            # 'a':forms.HiddenInput(),
            'c':forms.Select(attrs={
                'class':'ckt'
            }),
            'k':forms.Select(attrs={
                'class':'ckt'
            }),
            'title':forms.TextInput(attrs={
                'class':'ckt'
            }),
            'con':forms.TextInput(),
            'status':forms.CheckboxInput()

        }
    # def clean(self):  # 钩子函数首先执行
    #     cleaned_data = super().clean()

blog/self/views.py
from django.shortcuts import render,redirect,reverse
from authuser import authuser
from django.http import HttpResponse,JsonResponse
from userauth.models import User
from .models import Article
# Create your views here.
from authuser.authuser import Authuser
from .forms import Articleform
from django.views.decorators.csrf import csrf_exempt
@Authuser
def index(request):
    username=request.session.get("username",None)
    user=User.objects.filter(username=username).first()
    for item in user.article_set.all():
        ping=item.liuyan[:-1:1]
        ping1=ping.split("|")
    if request.method=="GET":
        return render(request,'self/myself.html',{'username':username,'user':user,'ping':ping1})
@Authuser
def Liuyan(request):
    username = request.session.get("username", None)
    if request.method == "GET":
        return render(request, "self/liuyan.html", {'username': username})
@Authuser
def SetInfo(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    if request.method == "GET":
        return render(request, "self/setinfo.html", {'username': username,'user':user})
@Authuser
def admin(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    if request.method == "GET":
        return render(request, "self/setinfo.html", {'username': username,'user':user})

# @Authuser
# def selfinfo(request):
#     username = request.session.get("username", None)
#     user = User.objects.filter(username=username).first()
#     if request.method == "GET":
#         return render(request, "self/setinfo.html", {'username': username, 'user': user})
@Authuser
def guanli(request):
    if request.method=='GET':
        username = request.session.get("username", None)
        return render(request,'self/index.html',{'username':username})

@Authuser
def myselfInfo(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    if request.method=='GET':
        return  render(request,'self/myselfInfo.html',{'user':user})

@Authuser
def upload(request):
    username = request.session.get("username", None)
    if request.method=="POST":
        img=request.FILES['img']
        name=request.POST.get('name')
        tel=request.POST.get('tel')
        email=request.POST.get('email')
        password=request.POST.get('password')
        # print(dir(img))
        with open('media/userhead/%s'%img.name,'wb+') as destination:
            for chunk in img.chunks():
                destination.write(chunk)
        User.objects.filter(username=username).update(username=name, tel=tel, email=email, password=password,img='/media/userhead/%s' % img.name)
        return redirect(reverse("self:myselfInfo"))
# @Authuser
# def Addarticle(request):
#     username = request.session.get("username", None)
#     if request.method=="GET":
#         aid = User.objects.filter(username=username).first().id
#         form = Articleform({'a': aid})
#         return render(request,'self/Addarticle.html',{'form':form})
#     else:
#         # print(request.POST)打印请求回来的信息
#         form=Articleform(request.POST)
#         #print(form.errors)    #打印form验证出现的问题
#         if form.is_valid():
#             # obj=form.save(commit=False)
#             # obj.a.add(aid)
#             # obj.save()
#             form.save()
#         return render(request,'self/Addarticle.html',{'form':form})
@Authuser
def Addarticle(request):
    username = request.session.get("username", None)
    if request.method=="GET":
        form = Articleform()
        return render(request,'self/Addarticle.html',{'form':form})
    else:
        # print(request.POST)打印请求回来的信息
        form=Articleform(request.POST)
        #print(form.errors)    #打印form验证出现的问题
        if form.is_valid():
            aid = User.objects.filter(username=username).first().id
            obj=form.save(commit=False)
            obj.a_id=aid
            obj.save()
        return render(request,'self/Addarticle.html',{'form':form})
@Authuser
def Lookarticle(request):
    username = request.session.get("username", None)
    user=User.objects.filter(username=username).first()
    articles=user.article_set.all()
    if request.method=="GET":
        return render(request,'self/Lookarticle.html',{'articles':articles})
@Authuser
def Delarticle(request,id):
    Article.objects.filter(id=id).delete()
    return redirect(reverse("self:Lookarticle"))
@Authuser
def XQarticle(request,id):
    article=Article.objects.filter(id=id).first()
    return render(request,"self/XQarticle.html",{'article':article})
@Authuser
def Pinglun(request,id):
    pinglun=request.POST.get("pinglun")
    import jieba
    import re
    import numpy as np
    from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
    from sklearn.feature_extraction.text import TfidfVectorizer

    def textParse1(lines):
        lines = re.sub(r'[a-zA-Z.【】0-9、。，@（）+""“”,:<>()：|？?\[\]\-/！…~\*\n]', '', lines)
        words = jieba.lcut(lines)
        new = [[w for w in words if len(w)>1]]
        document = [" ".join(sent) for sent in new]
        return document

    wordlist = []
    classlist = []
    for i in range(127):
        wordlist_s = textParse1(open('media/shuju/laji/%d.txt' % i, encoding='utf8').read())
        wordlist.append(','.join(wordlist_s))
        classlist.append(1)
    for i in range(29):
        wordlist_s = textParse1(open('media/shuju/zhengchang/%d.txt' % i, encoding='utf8').read())
        wordlist.append(','.join(wordlist_s))
        classlist.append(0)
    tfidf1 = TfidfVectorizer()
    result1 = tfidf1.fit_transform(wordlist)
    result1 = result1.toarray()
    gn = GaussianNB()
    gn = gn.fit(np.array(result1), np.array(classlist))
    testWords = textParse1(pinglun)
    res1 = tfidf1.transform(testWords)
    res1 = res1.toarray()
    # print(type(gn.predict(res1)))
    # print(dir(gn.predict(res1)))
    # print(gn.predict(res1)[0])
    if gn.predict(res1)[0]==1:
        return HttpResponse("评论内容不符合规则,请审核后重新评论")
    else:
        article=Article.objects.filter(id=id).first()
        article.liuyan+=pinglun+"|"
        article.save()
        return redirect(reverse("self:index"))
@Authuser
@csrf_exempt
def LookPinglun(request):
    pass
    # if request.is_ajax():
    #     id=request.POST.get("id",None)
    #     obj=Article.objects.filter(id=id).first()
    #     str1=obj.liuyan
    #     print(type(str1))
    #     str2=str1[:-1]
    #     print(type(str2))

blog/self/templates/moban/guanliMoban.html
<!DOCTYPE HTML>
<html>
<head>
<title>Modern an Admin Panel Category Flat Bootstarp Resposive Website Template | Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Modern Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
{% load static %}
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link rel="stylesheet" type="text/css" href="http://www.jq22.com/jquery/bootstrap-3.3.4.css">
<!-- Custom CSS -->
<link href="{% static 'self/guanli/css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'self/guanli/css/lines.css' %}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href="http://www.jq22.com/jquery/font-awesome.4.6.0.css"> 
<!-- jQuery -->
<script src="http://www.jq22.com/jquery/jquery-1.10.2.js"></script>

<!---//webfonts--->  
<!-- Nav CSS -->
<link href="{% static 'self/guanli/css/custom.css' %}" rel="stylesheet">
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'self/guanli/js/metisMenu.min.js' %}"></script>
<script src="{% static 'self/guanli/js/custom.js' %}"></script>
<!-- Graph JavaScript -->
<script src="{% static 'self/guanli/js/d3.v3.js' %}"></script>
<script src="{% static 'self/guanli/js/rickshaw.js' %}"></script>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<style>
	.aa1{
		color:#fff;
		line-height: 51px;
		margin-left:5px;
	}
</style>
<div id="wrapper">
     <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">{{ username }}后台管理系统</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-nav navbar-right">
				<a href="{% url 'self:index' %}" class="aa1">返回</a>
				<a href="{% url 'auth:login' %}" class="aa1">退出登录</a>
			</ul>
			<form class="navbar-form navbar-right">
              <input type="text" class="form-control" value="Search..." onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Search...';}">
            </form>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw nav_icon"></i>权限管理</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-laptop nav_icon"></i>个人管理<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'self:myselfInfo' %}">个人信息管理</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-indent nav_icon"></i>文章管理<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'self:Addarticle' %}">发表文章</a>
                                </li>
                                <li>
                                    <a href="{% url 'self:Lookarticle' %}">查看文章</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        {% block main %}
        {% endblock %}
      <!-- /#page-wrapper -->
   </div>
    <!-- /#wrapper -->
    <!-- Bootstrap Core JavaScript -->
    <script src="http://www.jq22.com/jquery/bootstrap-3.3.4.js"></script>

</body>
<script>
    {#$("#img").on("change",function () {#}
    {#    alert(1)#}
    {#})#}
</script>
</html>

blog/self/templates/moban/mobanHtml.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>我的咳咳</title>
<meta name="keywords" content="个人博客" />
<meta name="description" content="个人博客" />
    {% load static %}
<link href="{% static 'self/css/styles.css' %}" rel="stylesheet">
{% block css %}
{% endblock %}


</head>
<style>
    .avatar a { display: block; padding-top: 97px; width: 160px; height: 63px; background: url({{ user.img }}) no-repeat; background-size: 160px 160px }
    .text{
        position: relative;
    }
    .sks{
        width:100%;
        height: 150px;
        position: absolute;
        left:0;
        bottom: 0;
        background: #fff;
        display: none;
    }
    .pinglun{
        margin-left: 10px;
        cursor: pointer;
        color: #a6a6a6;
    }
    .submitt{
        width: 80px;
        height: 30px;
        background: #9cf3ff;
        cursor: pointer;
    }
    .liu1{
        font-size: 21px;
    }
</style>
<body>
<header>
 <nav id="nav">
   <ul>
    <li><a href="{% url 'self:index' %}" id="nav_current">我的咳咳</a></li>
    <li><a href="{% url 'pingtai:index' %}">园子</a></li>
    <li><a href="#">消息</a></li>
   <li><a href="{% url 'self:liuyan' %}">留言</a></li>
    <li><a href="{% url 'self:setinfo' %}">设置</a></li>
       <li><a href="{% url 'self:guanli' %}">管理</a></li>
    <li><a href="{% url 'pingtai:Exitlogin' %}">退出登录</a></li>
   </ul>
  <script src="{% static 'self/js/silder.js' %}"></script><!--获取当前页导航 高亮显示标题-->
 </nav>
 </header>
 <div class="mainContent">
    <aside>
      <div class="avatar">
        <a href="#"><span>{{ username }}</span></a>
      </div>
      <section class="topspaceinfo">
        <h1>明天又是开心的一天！！！</h1>
        <p>Keep on going never give up...</p>
      </section>
      <div class="userinfo">
        <p class="q-fans"> 粉丝：<a href="#">167</a></p>
        <p class="btns"><a href="#" >私信</a><a href="#">相册</a><a href="#">存档</a></p>
      </div>
      <section class="newpic">
         <h2>最新照片</h2>
         <ul>
           <li><a href="#"><img src="{% static 'self/images/01.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/02.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/03.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/04.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/05.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/06.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/07.jpg' %}"></a></li>
           <li><a href="#"><img src="{% static 'self/images/08.jpg' %}"></a></li>
         </ul>
      </section>
      <section class="taglist">
         <h2>全部标签</h2>
         <ul>
           <li><a href="#">快乐风男</a></li>
           <li><a href="#">坚毅</a></li>
           <li><a href="#">study</a></li>
           <li><a href="#">青青唠叨</a></li>
        </ul>
      </section>
    </aside>
    {% block main %}

    {% endblock %}
 </div>
<footer>
   <div class="footavatar">
     <img src={{ user.img }} class="footphoto" >
     <ul class="footinfo">
       <p class="fname"><a href="/dancesmile" >{{ username }}</a>  </p>
       <p class="finfo">性别：男 年龄：23岁</p>
       <p>现居：北京朝阳</p></ul>
   </div>
   <section class="visitor">
     <h2>最近访客</h2>
      <ul>
        <li><a href="#"><img src="{% static 'self/images/s0.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s1.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s2.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s3.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s5.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s6.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s7.jpg' %}"></a></li>
        <li><a href="#"><img src="{% static 'self/images/s8.jpg' %}"></a></li>
      </ul>
   </section>
   <div class="Copyright">
     <ul>
       <a href="#">帮助中心</a><a href="#">空间客服</a><a href="#">投诉中心</a><a href="#">空间协议</a>
     </ul>
     <p>Design by DanceSmile</p>
   </div>
 </footer>
</body>
</html>
<script src="{% static 'self/js/jquery-3.2.1.js' %}"></script>
<script>
     $(".pinglun").on("click",function () {
        $(".sks").css("display","block")
    })
     $.ajaxSetup({
        data:{csrfmiddlewaretoken:'{{ csrf_token }}'},
    });
     function look(id){
          $.ajax({
                type:'POST',
                url:'/self/LookPinglun/',
                data:{id:id},
                success:function (e) {
                    alert(e)
                }
             })
     }
</script>